title: David Hanny
author: David Hanny
subtitle: Spatial data science, machine learning, books, and writing

url: "https://hanny.dev"
baseurl: ""

footer_only_homepage: true
footer_url: "DEPRECATED"
footer_text: "DEPRECATED"

profile-picture: assets/profile_dh.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "index"
 - name: "Blog"
   link: "blog"
 - name: "Projects"
   link: "projects"
 - name: "Publications"
   absolute-link: "https://scholar.google.com/citations?user=iLWMR2oAAAAJ"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap