title: David Hanny
author: David
subtitle: Spatial data science, machine learning, books, and writing

url: "https://hanny.dev"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Scholar · ORCID · LinkedIn · Theme by rhl-bthr"

profile-picture: assets/profile_dh.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Blog"
   link: "blog"
 - name: "About"
   link: "index"
 - name: "Resume"
   absolute-link: "https://rahulbothra.com/cv.pdf"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap